// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4OfYDI98qTF1WEhXVlaa_p5X7dXrQwA',
    appId: '1:842150161295:web:887bd309873be89698b9fa',
    messagingSenderId: '842150161295',
    projectId: 'aid-tracker-40500',
    authDomain: 'aid-tracker-40500.firebaseapp.com',
    storageBucket: 'aid-tracker-40500.firebasestorage.app',
    measurementId: 'G-JFQLS4E50P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5c_n5gTscVBQhvMVICd9plbutrh5bGDY',
    appId: '1:842150161295:android:0209cabf9e019b1898b9fa',
    messagingSenderId: '842150161295',
    projectId: 'aid-tracker-40500',
    storageBucket: 'aid-tracker-40500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1y8mbv0zooDovBCCeSqOaUX8Lx9bcClo',
    appId: '1:842150161295:ios:adf99472e08df06e98b9fa',
    messagingSenderId: '842150161295',
    projectId: 'aid-tracker-40500',
    storageBucket: 'aid-tracker-40500.firebasestorage.app',
    iosBundleId: 'com.example.aidtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1y8mbv0zooDovBCCeSqOaUX8Lx9bcClo',
    appId: '1:842150161295:ios:adf99472e08df06e98b9fa',
    messagingSenderId: '842150161295',
    projectId: 'aid-tracker-40500',
    storageBucket: 'aid-tracker-40500.firebasestorage.app',
    iosBundleId: 'com.example.aidtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM4OfYDI98qTF1WEhXVlaa_p5X7dXrQwA',
    appId: '1:842150161295:web:7acbdbe7c22c52e598b9fa',
    messagingSenderId: '842150161295',
    projectId: 'aid-tracker-40500',
    authDomain: 'aid-tracker-40500.firebaseapp.com',
    storageBucket: 'aid-tracker-40500.firebasestorage.app',
    measurementId: 'G-35KTQ43PW1',
  );
}
